// const alarmToday = new AlarmClock();
// const alarm1= new AlarmClock();
// alarm1.addClock("15:31", () => console.log("звонок1"), 1);
// alarm1.addClock("15:27", () => console.log("звонок2"), 2);
// alarm1.addClock("15:33", () => console.log("звонок3"), 3);
// console.log(alarm1.removeClock(2));
// console.log(alarm1.removeClock(2));
// alarm1.getCurrentFormattedTime();
// alarm1.addClock("15:32", () => console.log("звонок2"), 2);
// alarm1.start();
testCase();